# Generated by Django 2.2.3 on 2020-06-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(max_length=200)),
                ('container_id', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
